-- Custom type for the investment pipeline status
CREATE TYPE pipeline_status AS ENUM (
  'Idea',
  'Researching',
  'Ready to Invest',
  'Invested'
);

-- Custom type for the sentiment of a user's note
CREATE TYPE note_sentiment AS ENUM (
  'Positive',
  'Neutral',
  'Negative'
);

-- Custom type for the category of a user's note (SWOT+)
CREATE TYPE insight_type AS ENUM (
  'Strength',
  'Weakness',
  'Opportunity',
  'Threat',
  'General'
);

-- Custom type for the cells in the Explore notebook
CREATE TYPE cell_type AS ENUM (
  'Query',
  'AI_Response'
);

-- Stores the master list of all companies
CREATE TABLE public.companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker VARCHAR(10) NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT,
  industry TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
CREATE INDEX idx_companies_ticker ON public.companies(ticker);

-- Links a user to a company and tracks its status in their pipeline
CREATE TABLE public.pipeline_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  status pipeline_status NOT NULL DEFAULT 'Idea',
  cost_basis NUMERIC(12, 2),
  shares_held NUMERIC(12, 4),
  invested_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  UNIQUE (user_id, company_id)
);
CREATE INDEX idx_pipeline_items_user_id ON public.pipeline_items(user_id);
CREATE INDEX idx_pipeline_items_status ON public.pipeline_items(status);

CREATE TABLE public.notebooks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
CREATE INDEX idx_notebooks_user_id ON public.notebooks(user_id);

CREATE TABLE public.notebook_cells (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notebook_id BIGINT NOT NULL REFERENCES public.notebooks(id) ON DELETE CASCADE,
  cell_type cell_type NOT NULL,
  content JSONB NOT NULL, -- This column now stores structured data
  cell_order INT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);
CREATE INDEX idx_notebook_cells_notebook_id ON public.notebook_cells(notebook_id);

--
-- IMPLEMENTATION NOTE FOR `notebook_cells.content`
--
-- When `cell_type` is 'Query', the JSONB can be simple:
-- { "text": "User's question goes here..." }
--
-- When `cell_type` is 'AI_Response', the JSONB will have a richer structure
-- to include the confidence score and justification:
-- {
--   "answer_text": "The main text of the AI's answer.",
--   "confidence_score": 70,
--   "confidence_justification": "This is a speculative forecast based on historical data and optimistic guidance.",
--   "evidence_sources": [
--     { "type": "RAG", "source": "The Intelligent Investor, Ch. 5" },
--     { "type": "API", "source": "Company Financials" }
--   ]
-- }
--