/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PipelineIndexRouteImport } from './routes/pipeline/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'

const PipelineIndexRoute = PipelineIndexRouteImport.update({
  id: '/pipeline/',
  path: '/pipeline/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/explore': typeof ExploreIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/pipeline': typeof PipelineIndexRoute
}
export interface FileRoutesByTo {
  '/explore': typeof ExploreIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/pipeline': typeof PipelineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/explore/': typeof ExploreIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/pipeline/': typeof PipelineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/explore' | '/knowledge' | '/pipeline'
  fileRoutesByTo: FileRoutesByTo
  to: '/explore' | '/knowledge' | '/pipeline'
  id: '__root__' | '/explore/' | '/knowledge/' | '/pipeline/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ExploreIndexRoute: typeof ExploreIndexRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  PipelineIndexRoute: typeof PipelineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pipeline/': {
      id: '/pipeline/'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ExploreIndexRoute: ExploreIndexRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  PipelineIndexRoute: PipelineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
