

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."cell_type" AS ENUM (
    'Query',
    'AI_Response'
);


ALTER TYPE "public"."cell_type" OWNER TO "postgres";


CREATE TYPE "public"."insight_type" AS ENUM (
    'Strength',
    'Weakness',
    'Opportunity',
    'Threat',
    'General'
);


ALTER TYPE "public"."insight_type" OWNER TO "postgres";


CREATE TYPE "public"."note_sentiment" AS ENUM (
    'Positive',
    'Neutral',
    'Negative'
);


ALTER TYPE "public"."note_sentiment" OWNER TO "postgres";


CREATE TYPE "public"."pipeline_status" AS ENUM (
    'Idea',
    'Researching',
    'Ready to Invest',
    'Invested'
);


ALTER TYPE "public"."pipeline_status" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."companies" (
    "id" bigint NOT NULL,
    "ticker" character varying(10) NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "industry" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."companies" OWNER TO "postgres";


ALTER TABLE "public"."companies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."companies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."notebook_cells" (
    "id" bigint NOT NULL,
    "notebook_id" bigint NOT NULL,
    "cell_type" "public"."cell_type" NOT NULL,
    "content" "jsonb" NOT NULL,
    "cell_order" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."notebook_cells" OWNER TO "postgres";


ALTER TABLE "public"."notebook_cells" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notebook_cells_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."notebooks" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."notebooks" OWNER TO "postgres";


ALTER TABLE "public"."notebooks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notebooks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pipeline_items" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "company_id" bigint NOT NULL,
    "status" "public"."pipeline_status" DEFAULT 'Idea'::"public"."pipeline_status" NOT NULL,
    "cost_basis" numeric(12,2),
    "shares_held" numeric(12,4),
    "invested_date" "date",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."pipeline_items" OWNER TO "postgres";


ALTER TABLE "public"."pipeline_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pipeline_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."companies"
    ADD CONSTRAINT "companies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."companies"
    ADD CONSTRAINT "companies_ticker_key" UNIQUE ("ticker");



ALTER TABLE ONLY "public"."notebook_cells"
    ADD CONSTRAINT "notebook_cells_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notebooks"
    ADD CONSTRAINT "notebooks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pipeline_items"
    ADD CONSTRAINT "pipeline_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pipeline_items"
    ADD CONSTRAINT "pipeline_items_user_id_company_id_key" UNIQUE ("user_id", "company_id");



CREATE INDEX "idx_companies_ticker" ON "public"."companies" USING "btree" ("ticker");



CREATE INDEX "idx_notebook_cells_notebook_id" ON "public"."notebook_cells" USING "btree" ("notebook_id");



CREATE INDEX "idx_notebooks_user_id" ON "public"."notebooks" USING "btree" ("user_id");



CREATE INDEX "idx_pipeline_items_status" ON "public"."pipeline_items" USING "btree" ("status");



ALTER TABLE ONLY "public"."notebook_cells"
    ADD CONSTRAINT "notebook_cells_notebook_id_fkey" FOREIGN KEY ("notebook_id") REFERENCES "public"."notebooks"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."notebooks"
    ADD CONSTRAINT "notebooks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pipeline_items"
    ADD CONSTRAINT "pipeline_items_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pipeline_items"
    ADD CONSTRAINT "pipeline_items_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."companies" TO "anon";
GRANT ALL ON TABLE "public"."companies" TO "authenticated";
GRANT ALL ON TABLE "public"."companies" TO "service_role";



GRANT ALL ON SEQUENCE "public"."companies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."companies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."companies_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."notebook_cells" TO "anon";
GRANT ALL ON TABLE "public"."notebook_cells" TO "authenticated";
GRANT ALL ON TABLE "public"."notebook_cells" TO "service_role";



GRANT ALL ON SEQUENCE "public"."notebook_cells_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notebook_cells_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notebook_cells_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."notebooks" TO "anon";
GRANT ALL ON TABLE "public"."notebooks" TO "authenticated";
GRANT ALL ON TABLE "public"."notebooks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."notebooks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notebooks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notebooks_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pipeline_items" TO "anon";
GRANT ALL ON TABLE "public"."pipeline_items" TO "authenticated";
GRANT ALL ON TABLE "public"."pipeline_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pipeline_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pipeline_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pipeline_items_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
